
package Meal_management;

import java.awt.AlphaComposite;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.HTML;
import javax.swing.text.html.parser.DTDConstants;


public class Dashboard extends javax.swing.JFrame{
    
    
  
    String url="jdbc:mysql://localhost/users_db";
    String db_uname="root";
    String db_Password="";
    
    
    

    public Dashboard() {
        this.setVisible(true);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setBounds(300,100,616,415);
        
        
        
        //retrieving data function calling
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        Home_panel = new javax.swing.JPanel();
        refresh_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        total_bazar_field = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        meal_rate_field = new javax.swing.JLabel();
        total_meal_field = new javax.swing.JLabel();
        total_member_field = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Dashboard_control = new javax.swing.JTabbedPane();
        Add_member_panel = new javax.swing.JPanel();
        name_field = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        room_no_field = new javax.swing.JTextField();
        mobile_no_field = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        add_member_table = new javax.swing.JTable();
        Add_btn = new javax.swing.JButton();
        Cancel_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        Add_meal_panel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        meal_datechooser = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        member_select_for_meal = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        breakfast_field = new javax.swing.JTextField();
        lunch_field = new javax.swing.JTextField();
        dinner_field = new javax.swing.JTextField();
        update_meal_btn = new javax.swing.JButton();
        save_meal_btn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        addmeal_table = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        Bazar_panel = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        bazar_datechooser = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        member_select_for_bazar = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        bazar_cost_field = new javax.swing.JTextField();
        update_bazar_btn = new javax.swing.JButton();
        save_bazar_btn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bazar_table = new javax.swing.JTable();
        Member_contribution_panel = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        datechooser_for_member_contribution = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        member_selection_for_payment = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        given_amount_field = new javax.swing.JTextField();
        given_amount_update_btn = new javax.swing.JButton();
        given_amount_save_btn = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        member_total_contribution_table = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        member_contribution_table = new javax.swing.JTable();
        Monthly_closing_panel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        total_meal_label = new javax.swing.JLabel();
        total_bazar_label = new javax.swing.JLabel();
        meal_rate_label = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        monthly_closing_table = new javax.swing.JTable();
        Calculate_btn = new javax.swing.JButton();
        Logout_button = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Total Member =");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Total meal(this month) =");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total Bazar =");

        total_bazar_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_bazar_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        total_bazar_field.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Meal Rate =");

        meal_rate_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        meal_rate_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        meal_rate_field.setText("0");

        total_meal_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_meal_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        total_meal_field.setText("0");

        total_member_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_member_field.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        total_member_field.setText("0");

        logout_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logout_btn.setText("Logout");
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_btnMouseClicked(evt);
            }
        });
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Home_panelLayout = new javax.swing.GroupLayout(Home_panel);
        Home_panel.setLayout(Home_panelLayout);
        Home_panelLayout.setHorizontalGroup(
            Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_panelLayout.createSequentialGroup()
                .addComponent(refresh_btn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(Home_panelLayout.createSequentialGroup()
                .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Home_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(total_meal_field, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(total_bazar_field, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(meal_rate_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(total_member_field, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Home_panelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(logout_btn)))
                .addGap(24, 184, Short.MAX_VALUE))
        );
        Home_panelLayout.setVerticalGroup(
            Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Home_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(refresh_btn)
                .addGap(33, 33, 33)
                .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_member_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_meal_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total_bazar_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meal_rate_field, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(logout_btn)
                .addGap(32, 32, 32))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        Dashboard_control.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Dashboard_controlMouseClicked(evt);
            }
        });

        name_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        name_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        name_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_fieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Name :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Username :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Room no :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Mobile no :");

        username_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        username_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        room_no_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        room_no_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        room_no_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room_no_fieldActionPerformed(evt);
            }
        });

        mobile_no_field.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mobile_no_field.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        mobile_no_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_no_fieldActionPerformed(evt);
            }
        });

        jScrollPane3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane3MouseClicked(evt);
            }
        });

        add_member_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Username", "Room no", "Mobile no"
            }
        ));
        add_member_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_member_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(add_member_table);

        Add_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Add_btn.setText("ADD");
        Add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_btnActionPerformed(evt);
            }
        });

        Cancel_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancel_btn.setText("CANCEL");
        Cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_btnActionPerformed(evt);
            }
        });

        delete_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        update_btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        update_btn.setText("UPDATE");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Add_member_panelLayout = new javax.swing.GroupLayout(Add_member_panel);
        Add_member_panel.setLayout(Add_member_panelLayout);
        Add_member_panelLayout.setHorizontalGroup(
            Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_member_panelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(room_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobile_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancel_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Add_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(131, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        Add_member_panelLayout.setVerticalGroup(
            Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_member_panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Add_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(username_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Cancel_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(room_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(delete_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Add_member_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mobile_no_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(update_btn))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
        );

        Dashboard_control.addTab("Add member", Add_member_panel);

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        meal_datechooser.setToolTipText("Select date");
        meal_datechooser.setDateFormatString(" d-MM- yyyy");
        meal_datechooser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                meal_datechooserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                meal_datechooserFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Select member");

        member_select_for_meal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_select_for_mealActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Breakfast");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Lunch");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Dinner");

        breakfast_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                breakfast_fieldActionPerformed(evt);
            }
        });

        update_meal_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update_meal_btn.setText("Update");
        update_meal_btn.setHideActionText(true);
        update_meal_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        update_meal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_meal_btnActionPerformed(evt);
            }
        });

        save_meal_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save_meal_btn.setText("Save");
        save_meal_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_meal_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dinner_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(meal_datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(breakfast_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lunch_field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(member_select_for_meal, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(update_meal_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(save_meal_btn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(meal_datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(member_select_for_meal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(breakfast_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lunch_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dinner_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_meal_btn)
                    .addComponent(save_meal_btn))
                .addGap(63, 63, 63))
        );

        addmeal_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "User", "Breakfast", "Lunch", "Dinner"
            }
        ));
        addmeal_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addmeal_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(addmeal_table);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Meal Table");

        javax.swing.GroupLayout Add_meal_panelLayout = new javax.swing.GroupLayout(Add_meal_panel);
        Add_meal_panel.setLayout(Add_meal_panelLayout);
        Add_meal_panelLayout.setHorizontalGroup(
            Add_meal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Add_meal_panelLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Add_meal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Add_meal_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)))
        );
        Add_meal_panelLayout.setVerticalGroup(
            Add_meal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Add_meal_panelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        Dashboard_control.addTab("Add meal", Add_meal_panel);

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));

        bazar_datechooser.setDateFormatString("dd-MM-yyyy");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Select member");

        member_select_for_bazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_select_for_bazarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Cost");

        update_bazar_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update_bazar_btn.setText("Update");
        update_bazar_btn.setHideActionText(true);
        update_bazar_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        update_bazar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_bazar_btnActionPerformed(evt);
            }
        });

        save_bazar_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        save_bazar_btn.setText("Save");
        save_bazar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_bazar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(member_select_for_bazar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bazar_cost_field)
                        .addComponent(bazar_datechooser, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(update_bazar_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save_bazar_btn)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(bazar_datechooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(member_select_for_bazar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel15)
                .addGap(15, 15, 15)
                .addComponent(bazar_cost_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_bazar_btn)
                    .addComponent(save_bazar_btn))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Bazar");

        bazar_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "User", "Cost"
            }
        ));
        bazar_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bazar_tableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(bazar_table);

        javax.swing.GroupLayout Bazar_panelLayout = new javax.swing.GroupLayout(Bazar_panel);
        Bazar_panel.setLayout(Bazar_panelLayout);
        Bazar_panelLayout.setHorizontalGroup(
            Bazar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Bazar_panelLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Bazar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Bazar_panelLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Bazar_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        Bazar_panelLayout.setVerticalGroup(
            Bazar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Bazar_panelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        Dashboard_control.addTab("Bazar", Bazar_panel);

        jPanel12.setBackground(new java.awt.Color(153, 153, 153));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Select member");

        member_selection_for_payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                member_selection_for_paymentActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Given amount(TK)");

        given_amount_update_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        given_amount_update_btn.setText("Update");
        given_amount_update_btn.setHideActionText(true);
        given_amount_update_btn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        given_amount_update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                given_amount_update_btnActionPerformed(evt);
            }
        });

        given_amount_save_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        given_amount_save_btn.setText("Save");
        given_amount_save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                given_amount_save_btnActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Total contribution :");

        member_total_contribution_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Amount"
            }
        ));
        member_total_contribution_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                member_total_contribution_tableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(member_total_contribution_table);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17)
                        .addComponent(member_selection_for_payment, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)
                        .addComponent(given_amount_field)
                        .addComponent(datechooser_for_member_contribution, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(given_amount_update_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(given_amount_save_btn))
                    .addComponent(jLabel19))
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(datechooser_for_member_contribution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(member_selection_for_payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(given_amount_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(given_amount_update_btn)
                    .addComponent(given_amount_save_btn))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Given Amount");

        member_contribution_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "User", "Amount(TK)"
            }
        ));
        member_contribution_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                member_contribution_tableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(member_contribution_table);
        if (member_contribution_table.getColumnModel().getColumnCount() > 0) {
            member_contribution_table.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout Member_contribution_panelLayout = new javax.swing.GroupLayout(Member_contribution_panel);
        Member_contribution_panel.setLayout(Member_contribution_panelLayout);
        Member_contribution_panelLayout.setHorizontalGroup(
            Member_contribution_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Member_contribution_panelLayout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(Member_contribution_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Member_contribution_panelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addGroup(Member_contribution_panelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );
        Member_contribution_panelLayout.setVerticalGroup(
            Member_contribution_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Member_contribution_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        Dashboard_control.addTab("Member's Contribution", Member_contribution_panel);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Total Bazar =");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Total meal =");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Meal rate =");

        total_meal_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_meal_label.setText("00");

        total_bazar_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_bazar_label.setText("00");

        meal_rate_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        meal_rate_label.setText("00");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("(-) = manager have to pay to member");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("(+) = member have to pay to manager");

        monthly_closing_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", "Total meal", "Total given", "Remarks"
            }
        ));
        jScrollPane8.setViewportView(monthly_closing_table);

        Calculate_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Calculate_btn.setText("Calculate");
        Calculate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculate_btnActionPerformed(evt);
            }
        });

        Logout_button.setText("Logout");
        Logout_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logout_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Monthly_closing_panelLayout = new javax.swing.GroupLayout(Monthly_closing_panel);
        Monthly_closing_panel.setLayout(Monthly_closing_panelLayout);
        Monthly_closing_panelLayout.setHorizontalGroup(
            Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                        .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                                .addComponent(meal_rate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(153, 153, 153)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                                .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_bazar_label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                                        .addComponent(total_meal_label, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(Calculate_btn)))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        Monthly_closing_panelLayout.setVerticalGroup(
            Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                        .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(total_meal_label)
                                    .addComponent(Calculate_btn)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Monthly_closing_panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(total_bazar_label, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(Monthly_closing_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Logout_button)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Monthly_closing_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(meal_rate_label)
                    .addComponent(jLabel25))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
        );

        Dashboard_control.addTab("Monthly closing", Monthly_closing_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Dashboard_control)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Dashboard_control, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Dashboard_controlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard_controlMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Dashboard_controlMouseClicked

    private void given_amount_update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_given_amount_update_btnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tableModel = (DefaultTableModel) member_contribution_table.getModel();
       int SelectedRowIndex =member_contribution_table.getSelectedRow();
       
       SimpleDateFormat dateFormat =new SimpleDateFormat("dd-MM-yyyy");
          String date =dateFormat.format(datechooser_for_member_contribution.getDate());
          
            String Data[]={date,member_selection_for_payment.getSelectedItem().toString(),given_amount_field.getText()};
       tableModel.setValueAt(Data[0],SelectedRowIndex, 0);
       tableModel.setValueAt(Data[1],SelectedRowIndex, 1);
       tableModel.setValueAt(Data[2],SelectedRowIndex, 2);
      
    }//GEN-LAST:event_given_amount_update_btnActionPerformed

    private void member_selection_for_paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_selection_for_paymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_selection_for_paymentActionPerformed

    private void update_bazar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_bazar_btnActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tableModel = (DefaultTableModel) bazar_table.getModel();
       int SelectedRowIndex =bazar_table.getSelectedRow();
       // String Data[]={name_field.getText(),username_field.getText(),room_no_field.getText(),mobile_no_field.getText()};
       SimpleDateFormat dateFormat =new SimpleDateFormat("dd-MM-yyyy");
          String date =dateFormat.format(bazar_datechooser.getDate());
          
            String Data[]={date,member_select_for_bazar.getSelectedItem().toString(),bazar_cost_field.getText()};
       tableModel.setValueAt(Data[0],SelectedRowIndex, 0);
       tableModel.setValueAt(Data[1],SelectedRowIndex, 1);
       tableModel.setValueAt(Data[2],SelectedRowIndex, 2);
   
    }//GEN-LAST:event_update_bazar_btnActionPerformed

    private void member_select_for_bazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_select_for_bazarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_select_for_bazarActionPerformed

    private void update_meal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_meal_btnActionPerformed
        // TODO add your handling code here:
           DefaultTableModel tableModel = (DefaultTableModel) addmeal_table.getModel();
       int SelectedRowIndex =addmeal_table.getSelectedRow();
       
       SimpleDateFormat dateFormat =new SimpleDateFormat("dd-MM-yyyy");
          String date =dateFormat.format(meal_datechooser.getDate());
          
          String Data[]={date,member_select_for_meal.getSelectedItem().toString(),breakfast_field.getText(),lunch_field.getText(),dinner_field.getText()};
    
        
          
       tableModel.setValueAt(Data[0],SelectedRowIndex, 0);
       tableModel.setValueAt(Data[1],SelectedRowIndex, 1);
       tableModel.setValueAt(Data[2],SelectedRowIndex, 2);
       tableModel.setValueAt(Data[3],SelectedRowIndex, 3);
       tableModel.setValueAt(Data[4],SelectedRowIndex, 4);
       
    }//GEN-LAST:event_update_meal_btnActionPerformed

    private void breakfast_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_breakfast_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_breakfast_fieldActionPerformed

    private void member_select_for_mealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_member_select_for_mealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_member_select_for_mealActionPerformed

    private void meal_datechooserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_meal_datechooserFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_meal_datechooserFocusLost

    private void meal_datechooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_meal_datechooserFocusGained

    }//GEN-LAST:event_meal_datechooserFocusGained

    private void Cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_btnActionPerformed
        // TODO add your handling code here:
        name_field.setText(null);
        username_field.setText(null);
        room_no_field.setText(null);
        mobile_no_field.setText(null);
    }//GEN-LAST:event_Cancel_btnActionPerformed

    private void mobile_no_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_no_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_no_fieldActionPerformed

    private void room_no_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room_no_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_room_no_fieldActionPerformed

    private void name_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_fieldActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logout_btnActionPerformed

    private void logout_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(null, "Are you sue to Logout", "Logout", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION)
        {
            Login_form frame =new Login_form();
            frame.setVisible(true);
            this.setVisible(false);
            frame.setBounds(300, 100, 500, 420);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setResizable(false);
            frame.setTitle("Login form");
        }
    }//GEN-LAST:event_logout_btnMouseClicked

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) add_member_table.getModel();
        try {
            int SelectedRowIndex =add_member_table.getSelectedRow();
            String uname= tableModel.getValueAt(SelectedRowIndex, 1).toString();
            
            tableModel.removeRow(SelectedRowIndex);
            
            
            //removing the item from every jcombo box
            member_select_for_meal.removeItem(uname);
            member_select_for_bazar.removeItem(uname);
            member_selection_for_payment.removeItem(uname);
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Select a row first", "", 0);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void Add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_btnActionPerformed
        if(name_field.getText().equals("")||username_field.getText().equals("")||room_no_field.getText().equals("")||mobile_no_field.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter all data", "Warning", 2);
        }
        else
        {
            
            //checking whether username has already used or not
            mysql_connector obj = new  mysql_connector();
            String query="Select *from add_member";
            
            int count = obj.signup_checker(query,username_field.getText());
            if(count!=0)
            {
                JOptionPane.showMessageDialog(null, "This username is already taken");
                
            }
            else
            {
               String Data[]={name_field.getText(),username_field.getText(),room_no_field.getText(),mobile_no_field.getText()};
            
            //making available all member in every jcombo box 
            member_select_for_meal.addItem(username_field.getText());
            member_select_for_bazar.addItem(username_field.getText());
            member_selection_for_payment.addItem(username_field.getText());
          
          
            //Inserting to database
            String insertData ="INSERT INTO add_member (Name,Username , Mobile_no, Room_no) VALUES (?,?,?,?)";
            
            obj.insert(insertData,Data);
            
         
            DefaultTableModel tableModel = (DefaultTableModel) add_member_table.getModel();
            tableModel.addRow(Data);

            
            name_field.setText(null);
            username_field.setText(null);
            room_no_field.setText(null);
            mobile_no_field.setText(null); 
            }
 

        }
    }//GEN-LAST:event_Add_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) add_member_table.getModel();
       int SelectedRowIndex =add_member_table.getSelectedRow();
        String Data[]={name_field.getText(),username_field.getText(),room_no_field.getText(),mobile_no_field.getText()};
       tableModel.setValueAt(Data[0],SelectedRowIndex, 0);
       tableModel.setValueAt(Data[1],SelectedRowIndex, 1);
       tableModel.setValueAt(Data[2],SelectedRowIndex, 2);
       tableModel.setValueAt(Data[3],SelectedRowIndex, 3);
       
       
    
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void jScrollPane3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane3MouseClicked

    private void add_member_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_member_tableMouseClicked
        // TODO add your handling code here:
     DefaultTableModel tableModel = (DefaultTableModel) add_member_table.getModel();
    int SelectedRowIndex =add_member_table.getSelectedRow();
    name_field.setText(tableModel.getValueAt(SelectedRowIndex, 0).toString());
    username_field.setText(tableModel.getValueAt(SelectedRowIndex, 1).toString());
    room_no_field.setText(tableModel.getValueAt(SelectedRowIndex, 2).toString());
    mobile_no_field.setText(tableModel.getValueAt(SelectedRowIndex, 3).toString());

    }//GEN-LAST:event_add_member_tableMouseClicked

    private void save_bazar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_bazar_btnActionPerformed
        // TODO add your handling code here:
        
        
        
        
         SimpleDateFormat dateFormat =new SimpleDateFormat("dd-MM-yyyy");
          String date =dateFormat.format(bazar_datechooser.getDate());
          DefaultTableModel tableModel = (DefaultTableModel) bazar_table.getModel();
            String row[]={date,member_select_for_bazar.getSelectedItem().toString(),bazar_cost_field.getText()};
           tableModel.addRow(row);
           
           
           //inserting into database
           String insertData ="INSERT INTO bazar (Date,Username,Cost) VALUES (?,?,?)";
            mysql_connector obj = new  mysql_connector();
            obj.insert(insertData,row);
          
     
    }//GEN-LAST:event_save_bazar_btnActionPerformed

    private void bazar_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bazar_tableMouseClicked
       
            // TODO add your handling code here:
            
        //prev_bazar_cost_today=Integer.parseInt(bazar_cost_field.getText());
        
        
        
            DefaultTableModel tableModel = (DefaultTableModel) bazar_table.getModel();
            int SelectedRowIndex = bazar_table.getSelectedRow();
            
            
         /*   String datestrString = tableModel.getValueAt(SelectedRowIndex, 0).toString();
            Date date = null;
        try {
            date = new SimpleDateFormat("dd/MM/yyyy").parse(datestrString);
        } catch (ParseException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
            bazar_datechooser.setDate(date);
            
            */
            bazar_cost_field.setText(tableModel.getValueAt(SelectedRowIndex, 2).toString());
            String combosString = tableModel.getValueAt(SelectedRowIndex, 1).toString();
            
            for(int i=0;i<member_select_for_bazar.getItemCount();i++)
            {
                if(member_select_for_bazar.getItemAt(i).toString().equalsIgnoreCase(combosString))
                {
                    member_select_for_bazar.setSelectedIndex(i);
                }
            }    
         
        
    
        
    }//GEN-LAST:event_bazar_tableMouseClicked

    private void save_meal_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_meal_btnActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat =new SimpleDateFormat("dd-MM-yyyy");
          String date =dateFormat.format(meal_datechooser.getDate());
          
          DefaultTableModel tableModel = (DefaultTableModel) addmeal_table.getModel();
            String row[]={date,member_select_for_meal.getSelectedItem().toString(),breakfast_field.getText(),lunch_field.getText(),dinner_field.getText()};
           tableModel.addRow(row);
           
           
           //inserting into database
           String insertData ="INSERT INTO add_meal (Date,Username,Breakfast,Lunch,Dinner) VALUES (?,?,?,?,?)";
            mysql_connector obj = new  mysql_connector();
            obj.insert(insertData,row);
           
      
        
    }//GEN-LAST:event_save_meal_btnActionPerformed

    private void addmeal_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addmeal_tableMouseClicked
        // TODO add your handling code here:
        
            DefaultTableModel tableModel = (DefaultTableModel) addmeal_table.getModel();
            int SelectedRowIndex = addmeal_table.getSelectedRow();
            
            /*String datestrString = tableModel.getValueAt(SelectedRowIndex, 0).toString();
            Date date = null;
        try {
            date = new SimpleDateFormat("dd/MM/yyyy").parse(datestrString);
        } catch (ParseException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
            meal_datechooser.setDate(date);
          
           */
            String combosString = tableModel.getValueAt(SelectedRowIndex, 1).toString();
            
            for(int i=0;i<member_select_for_meal.getItemCount();i++)
            {
                if(member_select_for_meal.getItemAt(i).toString().equalsIgnoreCase(combosString))
                {
                    member_select_for_meal.setSelectedIndex(i);
                }
            }
            breakfast_field.setText(tableModel.getValueAt(SelectedRowIndex, 2).toString());
            lunch_field.setText(tableModel.getValueAt(SelectedRowIndex, 3).toString());
            dinner_field.setText(tableModel.getValueAt(SelectedRowIndex, 4).toString());
            
    
        
    }//GEN-LAST:event_addmeal_tableMouseClicked

    private void given_amount_save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_given_amount_save_btnActionPerformed
        // TODO add your handling code here:
        
         SimpleDateFormat dateFormat =new SimpleDateFormat("dd-MM-yyyy");
          String date =dateFormat.format(datechooser_for_member_contribution.getDate());
          DefaultTableModel tableModel = (DefaultTableModel) member_contribution_table.getModel();
         // int selectdrowindex=member_contribution_table.getSelectedRow();
            String row[]={date,member_selection_for_payment.getSelectedItem().toString(),given_amount_field.getText()};
           tableModel.addRow(row);
           //inserting into database
           String insertData ="INSERT INTO  member_contribution (Date,Username,Given_Amount) VALUES (?,?,?)";
           
            mysql_connector obj = new  mysql_connector();
            obj.insert(insertData,row);
            
            //insertdata2 is for total given table query
            String insertData2 ="INSERT INTO  user_total_given (Username,Total_given) VALUES (?,?)";
           
           
         //for total given amount of a member
           
           DefaultTableModel tableModel2 = (DefaultTableModel) member_total_contribution_table.getModel();
          String  member = member_selection_for_payment.getSelectedItem().toString();
          
          if(tableModel2.getRowCount()!=0)
          {   int amount_now=0,flag=0;
              for(int i=0;i<tableModel2.getRowCount();i++)
              {
                  String member_compare = tableModel2.getValueAt(i, 0).toString();
                  if(member_compare==member)
                  {
                      String prev_amount_String=tableModel2.getValueAt(i, 1).toString();
                      int prev_amount= Integer.parseInt(prev_amount_String);
                      int added_amount=Integer.parseInt(given_amount_field.getText());
                      amount_now=prev_amount+added_amount;
                      String amount_nowString = String.valueOf(amount_now);
                      tableModel2.setValueAt(amount_nowString, i, 1);
                      flag=1;
                      
                      
                      
                      break;
                    
                  }
                  
                  
              }
              if(flag==0)
              {
                  String amount_update[]={member,given_amount_field.getText()};
                tableModel2.addRow(amount_update);
                
               //inserting into database(table name:user total given)
                obj.insert(insertData2,amount_update);
                
                      
              }
              
          }
          else
          {
              String amount_update[] ={member,given_amount_field.getText()};
              tableModel2.addRow(amount_update);
              
              //inserting into database(table name:user total given)
              obj.insert(insertData2,amount_update);
              
          }
          
      
            
    }//GEN-LAST:event_given_amount_save_btnActionPerformed

    private void member_total_contribution_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_member_total_contribution_tableMouseClicked
        // TODO add your handling code here:
             
    }//GEN-LAST:event_member_total_contribution_tableMouseClicked

    private void member_contribution_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_member_contribution_tableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) member_contribution_table.getModel();
            int SelectedRowIndex = member_contribution_table.getSelectedRow();
            
         /*   String datestrString = tableModel.getValueAt(SelectedRowIndex, 0).toString();
            Date date = null;
        try {
            date = new SimpleDateFormat("dd/MM/yyyy").parse(datestrString);
        } catch (ParseException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
            
            bazar_datechooser.setDate(date);
            
            */
            given_amount_field.setText(tableModel.getValueAt(SelectedRowIndex, 2).toString());
            String combosString = tableModel.getValueAt(SelectedRowIndex, 1).toString();
            
            for(int i=0;i<member_selection_for_payment.getItemCount();i++)
            {
                if(member_selection_for_payment.getItemAt(i).toString().equalsIgnoreCase(combosString))
                {
                    member_selection_for_payment.setSelectedIndex(i);
                }
            }
    }//GEN-LAST:event_member_contribution_tableMouseClicked

    private void Calculate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculate_btnActionPerformed
        // TODO add your handling code here:
        
        int all_user_total_meal=0;
         
         int total_bazar =0;
         double meal_rate =0;
         double remarks;
    
        
        
        //inserting data to monthly closing table
        DefaultTableModel monthly_closingTableModel = (DefaultTableModel) monthly_closing_table.getModel();
        DefaultTableModel add_memberTableModel = (DefaultTableModel) add_member_table.getModel();
        DefaultTableModel add_mealTableModel = (DefaultTableModel) addmeal_table.getModel();
        DefaultTableModel member_total_contributionModel = (DefaultTableModel) member_total_contribution_table.getModel();
        
        
        
        //for printing username in monthly closing table
        try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) monthly_closing_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from add_member";
            ResultSet rs = stmt.executeQuery(query);
        
         while(rs.next())
        {
           String Data[]={rs.getString("Username"),"0","0","0"};
           
            tableModel.addRow(Data);
          
        }
               
        } catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }
       
        
        
        
      //for adding meal in monthly closing table and counting total meal  
     for(int i=0;i<monthly_closingTableModel.getRowCount();i++)   
     {
         
         String uname_from_closing_table=monthly_closingTableModel.getValueAt(i, 0).toString();
         int breakfast=0,lunch=0,dinner=0;
         int total_meal_of_a_user=0;
         
         
           try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) addmeal_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from add_meal";
            ResultSet rs = stmt.executeQuery(query);
        
         while(rs.next())
        {  String uname_from_dbase=rs.getString("Username");
         if(uname_from_closing_table.equals(uname_from_dbase))
         {
             
          breakfast = Integer.parseInt(rs.getString("Breakfast"));
          lunch = Integer.parseInt(rs.getString("Lunch"));
          dinner = Integer.parseInt(rs.getString("Dinner"));
          total_meal_of_a_user =total_meal_of_a_user+breakfast+lunch+dinner;
          
          
       
         }
           
        
        }
         String prev_meal = monthly_closingTableModel.getValueAt(i, 1).toString();
       
        
             if(prev_meal.equals(String.valueOf(total_meal_of_a_user)))
         {
           
           
         }
         else{
             monthly_closingTableModel.setValueAt(String.valueOf(total_meal_of_a_user), i, 1);
              
         
             all_user_total_meal =all_user_total_meal + total_meal_of_a_user;
             
         }
        
        }
          
           
           
           catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }
           total_meal_label.setText(String.valueOf(all_user_total_meal));
           
          
     
     }
     
     
     
     //for counting total bazar
     
     
     try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) bazar_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from bazar";
            ResultSet rs = stmt.executeQuery(query);
        
         while(rs.next())
        {
          int temp = Integer.parseInt(rs.getString("Cost"));
           total_bazar =total_bazar +temp;
        
        }
        total_bazar_label.setText(String.valueOf(total_bazar));
               
        } catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }  
     
    
     
     //Calculating meal rate......
     
    meal_rate =(1.0)* total_bazar/all_user_total_meal;
    String meal_rateString = String.format("%.2f", meal_rate);

    meal_rate_label.setText(meal_rateString);
     
     
     
   //for finding contribution
     
     
    for(int i=0;i<monthly_closingTableModel.getRowCount();i++)
    {
        String uname_from_closing_table=monthly_closingTableModel.getValueAt(i, 0).toString();
        
        int toatl_given =0;
         try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) member_total_contribution_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from  user_total_given";
            ResultSet rs = stmt.executeQuery(query);
        
        
            while(rs.next())
        {
            String uname_from_dbase=rs.getString("Username");
         if(uname_from_closing_table.equals(uname_from_dbase))
         {
           
           String total_given = rs.getString("Total_given");
             
             
             String prev_given = monthly_closingTableModel.getValueAt(i, 2).toString();
       
        
             if(prev_given.equals(total_given))
         {
           
          
         }
         else{
             monthly_closingTableModel.setValueAt(total_given, i, 2);
      
             
         }
       
         }

        }
               
        } catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }
    
    
    
    //final calcultation of every users remarks
    
    for(int i=0;i<monthly_closingTableModel.getRowCount();i++)
    {
        int total_meal=Integer.parseInt(monthly_closingTableModel.getValueAt(i, 1).toString());
        int total_given=Integer.parseInt(monthly_closingTableModel.getValueAt(i, 2).toString());
        remarks= (meal_rate*total_meal)-total_given;
        monthly_closingTableModel.setValueAt(String.format("%.2f", remarks), i, 3);
        
       
        
        
    }

     
    
     
        
   
         
       
       
       
    }//GEN-LAST:event_Calculate_btnActionPerformed

    private void Logout_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logout_buttonMouseClicked
        // TODO add your handling code here:
         int choice = JOptionPane.showConfirmDialog(null, "Are you sue to Logout", "Logout", JOptionPane.YES_NO_OPTION);
        if(choice == JOptionPane.YES_OPTION)
        {
            Login_form frame =new Login_form();
            frame.setVisible(true);
            this.setVisible(false);
            frame.setBounds(300, 100, 500, 420);
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setResizable(false);
            frame.setTitle("Login form");
        }
    }//GEN-LAST:event_Logout_buttonMouseClicked
   
    
    
    //retrieving data from database........
    
    public  void getdata_from_addmember()
    {
   try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) add_member_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from add_member";
            ResultSet rs = stmt.executeQuery(query);
        
         while(rs.next())
        {
           String Data[]={rs.getString("Name"),rs.getString("Username"),rs.getString("Room_no"),rs.getString("Mobile_no")};
           
            tableModel.addRow(Data);
            String uname=rs.getString("Username");
            
            member_select_for_meal.addItem(uname);
            member_select_for_bazar.addItem(uname);
            member_selection_for_payment.addItem(uname);
            
           
 
        }
               
        } catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }
       
        
    }
    
    
    
    public  void getdata_from_addmeal()
    {
   try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) addmeal_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from add_meal";
            ResultSet rs = stmt.executeQuery(query);
        
         while(rs.next())
        {
           String Data[]={rs.getString("Date"),rs.getString("Username"),rs.getString("Breakfast"),rs.getString("Lunch"),rs.getString("Dinner")};
           
            tableModel.addRow(Data);
           
        
        }
               
        } catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }
        
    }
    
    
    
    
    public  void getdata_from_bazar()
    {
   try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) bazar_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from bazar";
            ResultSet rs = stmt.executeQuery(query);
        
         while(rs.next())
        {
           String Data[]={rs.getString("Date"),rs.getString("Username"),rs.getString("Cost")};
           
            tableModel.addRow(Data);
           
        
        }
               
        } catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }   
    }
    
    
    
    
    public  void getdata_from_member_contribution()
    {
   try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) member_contribution_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from member_contribution";
            ResultSet rs = stmt.executeQuery(query);
        
         while(rs.next())
        {
           String Data[]={rs.getString("Date"),rs.getString("Username"),rs.getString("Given_Amount")};
           
            tableModel.addRow(Data);
           
        
        }
               
        } catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }   
    }
    
    
    
    
    public  void getdata_from_user_total_given()
    {
   try {   
           
            DefaultTableModel tableModel = (DefaultTableModel) member_total_contribution_table.getModel();
            
            Connection con = DriverManager.getConnection(url,db_uname,db_Password);
            java.sql.Statement stmt = con.createStatement();
            
            
            //for retrieving add_member table data
            String query="Select *from  user_total_given";
            ResultSet rs = stmt.executeQuery(query);
        
         while(rs.next())
        {
           String Data[]={rs.getString("Username"),rs.getString("Total_given")};
           
            tableModel.addRow(Data);
           
        
        }
               
        } catch (SQLException ex) {
            Logger.getLogger(mysql_connector.class.getName()).log(Level.SEVERE, null, ex);
            
        }   
    }
    
   
     
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
      Dashboard obj =new Dashboard();
      obj.getdata_from_addmember();
      obj.getdata_from_addmeal();
      obj.getdata_from_bazar();
      obj.getdata_from_member_contribution();
      obj.getdata_from_user_total_given();
      
      
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_btn;
    private javax.swing.JPanel Add_meal_panel;
    private javax.swing.JPanel Add_member_panel;
    private javax.swing.JPanel Bazar_panel;
    private javax.swing.JButton Calculate_btn;
    private javax.swing.JButton Cancel_btn;
    private javax.swing.JTabbedPane Dashboard_control;
    private javax.swing.JPanel Home_panel;
    private javax.swing.JButton Logout_button;
    private javax.swing.JPanel Member_contribution_panel;
    private javax.swing.JPanel Monthly_closing_panel;
    private javax.swing.JTable add_member_table;
    private javax.swing.JTable addmeal_table;
    private javax.swing.JTextField bazar_cost_field;
    private com.toedter.calendar.JDateChooser bazar_datechooser;
    private javax.swing.JTable bazar_table;
    private javax.swing.JTextField breakfast_field;
    private com.toedter.calendar.JDateChooser datechooser_for_member_contribution;
    private javax.swing.JButton delete_btn;
    private javax.swing.JTextField dinner_field;
    private javax.swing.JTextField given_amount_field;
    private javax.swing.JButton given_amount_save_btn;
    private javax.swing.JButton given_amount_update_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable4;
    private javax.swing.JButton logout_btn;
    private javax.swing.JTextField lunch_field;
    private com.toedter.calendar.JDateChooser meal_datechooser;
    private javax.swing.JLabel meal_rate_field;
    private javax.swing.JLabel meal_rate_label;
    private javax.swing.JTable member_contribution_table;
    private javax.swing.JComboBox member_select_for_bazar;
    private javax.swing.JComboBox member_select_for_meal;
    private javax.swing.JComboBox member_selection_for_payment;
    private javax.swing.JTable member_total_contribution_table;
    private javax.swing.JTextField mobile_no_field;
    private javax.swing.JTable monthly_closing_table;
    private javax.swing.JTextField name_field;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTextField room_no_field;
    private javax.swing.JButton save_bazar_btn;
    private javax.swing.JButton save_meal_btn;
    private javax.swing.JLabel total_bazar_field;
    private javax.swing.JLabel total_bazar_label;
    private javax.swing.JLabel total_meal_field;
    private javax.swing.JLabel total_meal_label;
    private javax.swing.JLabel total_member_field;
    private javax.swing.JButton update_bazar_btn;
    private javax.swing.JButton update_btn;
    private javax.swing.JButton update_meal_btn;
    private javax.swing.JTextField username_field;
    // End of variables declaration//GEN-END:variables

    
}
